style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/Mist3rBru/go-clack
options:
  sort: 'date'
  commits:
    sort_by: Scope
  commit_groups:
    group_by: Type
    sort_by: Custom
    title_order:
      - feat
      - fix
      - test
      - refactor
      - docs
      - chore
    title_maps:
      feat: ğŸš€ Features
      fix: ğŸ©¹ Fixes
      test: ğŸ§ª Tests
      refactor: ğŸ› ï¸ Refactors
      docs: ğŸ“– Documentation
      chore: ğŸ¡ Chore
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
